/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package myalgorithmsimulator;

import javax.swing.JOptionPane;

/**
 *
 * @author Kirushan Rasendran
 */
public class StartScreen extends javax.swing.JFrame {

    /**
     * Creates new form StartScreen
     */
    public StartScreen() {
        initComponents();
        this.Bubble.setVisible(false);
        this.Selectionsort.setVisible(false);
        Valueready.setVisible(false);
    }
    int values[] = new int[5];
    int maxsize = 5;
    String value1;
    String value2;
    String value3;
    String value4;
    String value5;
    Validation valid = new Validation();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Value1 = new javax.swing.JTextField();
        Value2 = new javax.swing.JTextField();
        Value3 = new javax.swing.JTextField();
        Value4 = new javax.swing.JTextField();
        Value5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Bubble = new javax.swing.JButton();
        Selectionsort = new javax.swing.JButton();
        Valueready = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(682, 380));

        jButton1.setText("Load");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Bubble.setText("Bubble Sort");
        Bubble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BubbleActionPerformed(evt);
            }
        });

        Selectionsort.setText("Selection Sort");
        Selectionsort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectionsortActionPerformed(evt);
            }
        });

        Valueready.setForeground(new java.awt.Color(255, 0, 0));
        Valueready.setText("Values ready for sorting");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(Value1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bubble)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Value2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Value3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Value4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(Value5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Selectionsort, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Valueready)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(Valueready)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Value1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Value2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Value3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Value4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Value5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bubble, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Selectionsort, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     /*
     * Loading Button Evetn
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        value1 = Value1.getText();
        value2 = Value2.getText();
        value3 = Value3.getText();
        value4 = Value4.getText();
        value5 = Value5.getText();
        if (value1.equals("") || value2.equals("") || value3.equals("") || value4.equals("") || value5.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter all the values");
        } else {
            boolean validre = valid.valid(value1, value2, value3, value4, value5);//returns true if the 
            //value had any characters 
            if (!validre) {
                /*
                 * Loading the values to the array
                 */
                try {
                    values[0] = Integer.parseInt(value1);       //Loading the values
                    values[1] = Integer.parseInt(value2);
                    values[2] = Integer.parseInt(value3);
                    values[3] = Integer.parseInt(value4);
                    values[4] = Integer.parseInt(value5);
                    Valueready.setVisible(true);
                    Value1.setText("");
                    Value2.setText("");
                    Value3.setText("");
                    Value4.setText("");
                    Value5.setText("");
                    this.Bubble.setVisible(true);
                    this.Selectionsort.setVisible(true);

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Please enter numbers no");
                }



//                for(int i=0;i<5;i++)
//                {
//                    System.out.println(values[i]);
//                }


            } else {
                JOptionPane.showMessageDialog(null, "please enter numbers");
            }

        }
        validate();
        repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BubbleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BubbleActionPerformed
        
        Sorting SortObj = new Sorting(values);
        SortObj.setParentFrame(this);
        SortObj.init();
        try {
            SortObj.BubbleSortcall();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        this.dispose();
    }//GEN-LAST:event_BubbleActionPerformed

    private void SelectionsortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectionsortActionPerformed
        Sorting SortObj = new Sorting(values);
        SortObj.setParentFrame(this);
        SortObj.init();
        try {
            SortObj.SelectionSortCall();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        this.dispose();
    }//GEN-LAST:event_SelectionsortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartScreen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bubble;
    private javax.swing.JButton Selectionsort;
    private javax.swing.JTextField Value1;
    private javax.swing.JTextField Value2;
    private javax.swing.JTextField Value3;
    private javax.swing.JTextField Value4;
    private javax.swing.JTextField Value5;
    private javax.swing.JLabel Valueready;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
